receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680

extensions:
  health_check:

exporters:
  elastic:
    apm_server_url: "http://apm-server:8200"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [elastic]