receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680

extensions:
  health_check:

exporters:
  elastic:
    apm_server_url: "<APM_SERVER_URL>"
    secret_token: "<SECRET_TOKEN>"

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [elastic]