apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-server
  labels:
    app: fleet-server
spec:
  selector:
    matchLabels:
      app: fleet-server
  template:
    metadata:
      labels:
        app: fleet-server
    spec:
      serviceAccountName: fleet-server
      containers:
      - name: fleet-server
        image: crispymoon123/otel-fleet-server:0.0.2
        ports:
        - containerPort: 8200
        - containerPort: 8220
---
apiVersion: v1
kind: Service
metadata:
  name: fleet-server
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200
    name: http
  - protocol: TCP
    port: 8220
    targetPort: 8220
    name: http2
  selector:
    app: fleet-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-server
  namespace: otel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-server
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleet-server
subjects:
- kind: ServiceAccount
  name: fleet-server
  namespace: otel
roleRef:
  kind: ClusterRole
  name: fleet-server
  apiGroup: rbac.authorization.k8s.io
