apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: crispymoon123/otel-hello-app:0.0.1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    name: http
  selector:
    app: hello-app